### ISSUE TITLE
Warlords Damage/Healing Tracker

### ISSUE THREAD

**Issue by PocketOfPockets** [unaussprechlich/HudPixelExtended#1]
The tracker no longer shows up. This is the reason many people of the warlords community use this mod. It would be cool to see it's return

**Comment by Eladkay** [comment]
I'm pretty sure I saw it, are you sure?

**Comment by Eladkay** [comment]
Screenshot I just took:
https://imgur.com/a/k26Ya

The issue is in your side.

**Comment by PocketOfPockets** [comment]
It wasn't working, but it is the the current update. All good. idk what was going on
