### ISSUE TITLE
Coin Counter, Kills, and Game Time resets on death.

### ISSUE THREAD

**Issue by PlayfulPiano** [unaussprechlich/HudPixelExtended#11]
Minecraft version: 1.8.9
Hudpixel version: 3.2.7
Other mods: Optifine 1.8.9 HD U H5, Forge 1.8.9 11.15.1.1722

In non-permanent death minigames (example: MW), coins, time, and kills reset on death.

**Comment by unaussprechlich** [comment]
@Eladkay
