### ISSUE TITLE
Double FPS and Ping

### ISSUE THREAD

**Issue by PocketOfPockets** [unaussprechlich/HudPixelExtended#2]
http://image.prntscr.com/image/33361b7a3ac94a1f91def40a903177b9.png
FPS and Ping show twice. I think it happens only after a game ends

**Comment by unaussprechlich** [comment]
Hey, i'm aware of this bug and will fix it for the next update. This bug is caused by the original HudPixel rendering System.

**Comment by Eladkay** [comment]
It disappears after a bit though. @unaussprechlich will fix it for the next hotfix and by the next minor I'll have the Modular GUI system ready.

**Comment by Eladkay** [comment]
Fixed 3dab306 (3.0.3)
