### ISSUE TITLE
Long Game name in FriendsDisplay overlaps with the gui

### ISSUE THREAD

**Issue by builder-247** [unaussprechlich/HudPixelExtended#7]
Suggested solution is to increase the width of the gui.

![ss 2016-10-28 at 03 52 02](https://cloud.githubusercontent.com/assets/14019974/19807091/2459a12a-9d27-11e6-98c9-045a9ffb82c6.jpg)

**Comment by Eladkay** [comment]
I don't get the problem. It goes slightly beyond the borders of the HUD. Why is that an issue?

**Comment by builder-247** [comment]
Because it looks bad... Nevermind then I thought you guys had some standards :P

**Comment by Eladkay** [comment]
We have standards but if we fix it by making the GUI bigger people will complain that it doesn't fit on smaller screens. People will always find something to complain about. If standards are so important, how about you fix it and send a PR?

**Comment by unaussprechlich** [comment]
I will just make the string shorter :P
