### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by MCwarlord1023** [unaussprechlich/HudPixelExtended#8]
I recently posted a thread on hypixel forums about a warlord's stat GUI but when I got hud pixel and started a warlord's game nothing showed up on my screen but my better debut mod which isn't related to hudpixel at all

**Comment by unaussprechlich** [comment]
Delete your config and update to the lastest version :) If you are using Optifine you have to disable "Fast Render". If that doesn't help join our discord server, you can get direct help there. Or post your logfiles, config and some Screenshots here ;) - i will leave this open for now
