### ISSUE TITLE
Crashes whenever i try to log into Hypixel

### ISSUE THREAD

**Issue by Minoritix** [unaussprechlich/HudPixelExtended#9]
Whenever i try to enter Hypixel, my game would stop responding. I tested without the mod and I can enter Hypixel. It is only v3.2.7 that crashes, the previous versions were working fine.

**Comment by Eladkay** [comment]
It's because @unaussprechlich went down. For now use lower versions, it will be fixed asap.

**Comment by Eladkay** [comment]
Seems to be fixed.
